// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        ElBtuuon: typeof import('element-plus/es')['ElBtuuon']
        ElButton: typeof import('element-plus/es')['ElButton']
        ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
        ElMenu: typeof import('element-plus/es')['ElMenu']
        ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
        ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
        ObDialog: typeof import('./src/components/obDialog/ObDialog.vue')['default']
        ObInput: typeof import('./src/components/obInput/ObInput.vue')['default']
        ObTablePage: typeof import('./src/components/obTable/ObTablePage.vue')['default']
        ObTabs: typeof import('./src/components/obTabs/ObTabs.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        SvgIcon: typeof import('./src/components/svgicon/SvgIcon.vue')['default']
    }
}

export {}
