/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ObDialog: typeof import('./src/components/obDialog/ObDialog.vue')['default']
    ObInput: typeof import('./src/components/obInput/ObInput.vue')['default']
    ObTablePage: typeof import('./src/components/obTable/ObTablePage.vue')['default']
    ObTabs: typeof import('./src/components/obTabs/ObTabs.vue')['default']
    ObUpload: typeof import('./src/components/obUpload/ObUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/svgicon/SvgIcon.vue')['default']
  }
}
